### ISSUE TITLE
Work List

### ISSUE THREAD

**Issue by Stargator** [Stargator/gregreda-jekylified#4]
- [ ] Add a Now Page - https://github.com/gjreda/gregreda.com/issues/11
- [ ] Add a contact form - https://github.com/gjreda/gregreda.com/issues/10
- [ ] Make Mailchimp form not look like crap - https://github.com/gjreda/gregreda.com/issues/9
- [ ] Move navbar icons logic to pelicanconf.py - https://github.com/gjreda/gregreda.com/issues/7
- [ ] Add some sort of projects/portfolio page - https://github.com/gjreda/gregreda.com/issues/4
- [ ] Invalidate CloudFront cache on rebuild - https://github.com/gjreda/gregreda.com/issues/2
